# Generated by Django 6.0.5 on 2026-06-02 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=128)),
                ('address', models.TextField(blank=True, null=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rooms_available', models.IntegerField(default=0)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_offset', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('default_available', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'code')},
            },
        ),
        migrations.CreateModel(
            name='HotelInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField(default=0)),
                ('last_sync_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='hotels.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelroomtype')),
            ],
            options={
                'unique_together': {('hotel', 'room_type')},
            },
        ),
    ]
