# Generated by Django 6.0.5 on 2026-06-02 05:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet')], max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', '-created_at'], name='payments_pa_booking_166590_idx'), models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx')],
            },
        ),
    ]
