# Generated by Django 6.0.5 on 2026-06-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=64, unique=True)),
                ('airline', models.CharField(max_length=128)),
                ('flight_number', models.CharField(blank=True, max_length=32, null=True)),
                ('source', models.CharField(blank=True, max_length=64, null=True)),
                ('destination', models.CharField(blank=True, max_length=64, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=64, null=True)),
                ('arrival_time', models.CharField(blank=True, max_length=64, null=True)),
                ('travel_class', models.CharField(blank=True, max_length=32, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
